before:
  hooks:
    - go mod download
builds:
- id: "health"
  binary: "grpc-health"
  main: "./cmd/grpc-health/main.go"
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  env:
  - CGO_ENABLED=0
archives:
- name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
